-- Crypto Trading Knowledge System Database Schema

-- Prices table: Raw OHLCV data from exchanges
CREATE TABLE IF NOT EXISTS prices (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    open DECIMAL(20, 8) NOT NULL,
    high DECIMAL(20, 8) NOT NULL,
    low DECIMAL(20, 8) NOT NULL,
    close DECIMAL(20, 8) NOT NULL,
    volume DECIMAL(20, 8) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(symbol, timestamp)
);

CREATE INDEX idx_prices_symbol_timestamp ON prices(symbol, timestamp DESC);

-- Features table: Computed technical indicators
CREATE TABLE IF NOT EXISTS features (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    ema20 DECIMAL(20, 8),
    ema50 DECIMAL(20, 8),
    rsi14 DECIMAL(10, 4),
    macd DECIMAL(20, 8),
    macd_signal DECIMAL(20, 8),
    macd_histogram DECIMAL(20, 8),
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(symbol, timestamp)
);

CREATE INDEX idx_features_symbol_timestamp ON features(symbol, timestamp DESC);

-- Trade Signals table: Buy/sell signals generated by strategy
CREATE TABLE IF NOT EXISTS trade_signals (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    signal_type VARCHAR(10) NOT NULL, -- 'BUY', 'SELL', 'HOLD'
    strength DECIMAL(5, 4), -- 0.0 to 1.0
    reason TEXT,
    features JSONB, -- Snapshot of features at signal time
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_trade_signals_symbol_timestamp ON trade_signals(symbol, timestamp DESC);
CREATE INDEX idx_trade_signals_type ON trade_signals(signal_type);

-- Orders table: Executed or simulated orders
CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    order_type VARCHAR(10) NOT NULL, -- 'MARKET', 'LIMIT'
    side VARCHAR(10) NOT NULL, -- 'BUY', 'SELL'
    quantity DECIMAL(20, 8) NOT NULL,
    price DECIMAL(20, 8),
    status VARCHAR(20) NOT NULL, -- 'PENDING', 'FILLED', 'CANCELLED', 'REJECTED'
    signal_id INTEGER REFERENCES trade_signals(id),
    executed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_orders_symbol ON orders(symbol);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

-- Positions table: Current holdings
CREATE TABLE IF NOT EXISTS positions (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    quantity DECIMAL(20, 8) NOT NULL,
    avg_entry_price DECIMAL(20, 8) NOT NULL,
    current_price DECIMAL(20, 8),
    unrealized_pnl DECIMAL(20, 8),
    updated_at TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_positions_symbol ON positions(symbol);

-- News Events table: External events that might impact trading
CREATE TABLE IF NOT EXISTS news_events (
    id SERIAL PRIMARY KEY,
    source VARCHAR(50) NOT NULL,
    title TEXT NOT NULL,
    url TEXT,
    published_at TIMESTAMP NOT NULL,
    sentiment VARCHAR(20), -- 'BULLISH', 'BEARISH', 'NEUTRAL'
    impact_score DECIMAL(5, 4), -- 0.0 to 1.0
    keywords TEXT[],
    raw_data JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_news_events_published ON news_events(published_at DESC);
CREATE INDEX idx_news_events_sentiment ON news_events(sentiment);
CREATE INDEX idx_news_events_impact ON news_events(impact_score DESC);

-- System Flags table: Control flags for system behavior
CREATE TABLE IF NOT EXISTS system_flags (
    id SERIAL PRIMARY KEY,
    flag_name VARCHAR(50) NOT NULL UNIQUE,
    flag_value BOOLEAN NOT NULL DEFAULT FALSE,
    reason TEXT,
    set_by VARCHAR(50),
    updated_at TIMESTAMP DEFAULT NOW(),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_system_flags_name ON system_flags(flag_name);

-- Initialize TRADE_PAUSE flag
INSERT INTO system_flags (flag_name, flag_value, reason, set_by)
VALUES ('TRADE_PAUSE', FALSE, 'Initial setup', 'system')
ON CONFLICT (flag_name) DO NOTHING;
